name: Build container

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker
      run: docker build -t sabito27/gachi-generator:$GITHUB_RUN_ID -f Dockerfile .
    - name: Push docker
      run: docker push sabito27/gachi-generator:$GITHUB_RUN_ID
